export const API_PREFIX = "/api";

export const API = {
  health: `${API_PREFIX}/health`,
  companies: `${API_PREFIX}/companies`,
  agents: `${API_PREFIX}/agents`,
  projects: `${API_PREFIX}/projects`,
  issues: `${API_PREFIX}/issues`,
  issueTreeControl: `${API_PREFIX}/issues/:issueId/tree-control`,
  issueTreeHolds: `${API_PREFIX}/issues/:issueId/tree-holds`,
  goals: `${API_PREFIX}/goals`,
  approvals: `${API_PREFIX}/approvals`,
  secrets: `${API_PREFIX}/secrets`,
  secretProviderConfigs: `${API_PREFIX}/secret-provider-configs`,
  secretProviderConfigDiscoveryPreview: `${API_PREFIX}/companies/:companyId/secret-provider-configs/discovery/preview`,
  costs: `${API_PREFIX}/costs`,
  activity: `${API_PREFIX}/activity`,
  dashboard: `${API_PREFIX}/dashboard`,
  sidebarBadges: `${API_PREFIX}/sidebar-badges`,
  sidebarPreferences: `${API_PREFIX}/sidebar-preferences`,
  invites: `${API_PREFIX}/invites`,
  joinRequests: `${API_PREFIX}/join-requests`,
  members: `${API_PREFIX}/members`,
  admin: `${API_PREFIX}/admin`,
  meetingRooms: {
    list: `${API_PREFIX}/companies/:companyId/meeting-rooms`,
    create: `${API_PREFIX}/companies/:companyId/meeting-rooms`,
    detail: `${API_PREFIX}/companies/:companyId/meeting-rooms/:roomId`,
    update: `${API_PREFIX}/companies/:companyId/meeting-rooms/:roomId`,
    participants: `${API_PREFIX}/companies/:companyId/meeting-rooms/:roomId/participants`,
    participant: `${API_PREFIX}/companies/:companyId/meeting-rooms/:roomId/participants/:participantId`,
    messages: `${API_PREFIX}/companies/:companyId/meeting-rooms/:roomId/messages`,
    summaries: `${API_PREFIX}/companies/:companyId/meeting-rooms/:roomId/summaries`,
    summary: `${API_PREFIX}/companies/:companyId/meeting-rooms/:roomId/summaries/:summaryId`,
    issueMeetingRooms: `${API_PREFIX}/companies/:companyId/issues/:issueId/meeting-rooms`,
    projectDocumentMeetingRooms: `${API_PREFIX}/companies/:companyId/projects/:projectId/documents/:documentId/meeting-rooms`,
  },
} as const;
